// Real Solana Devnet Collections
export const REAL_DEVNET_COLLECTIONS = [
  {
    id: 'solana-monkey-business',
    name: 'Solana Monkey Business',
    symbol: 'SMB',
    description: 'The first 5000 monkeys on Solana - now on devnet for testing',
    image: 'https://arweave.net/FPGAv1XnyZidnqquOdEbSY6_ES735ckcDTdaAtI7GFw',
    verified: true,
    floorPrice: 12.5,
    totalSupply: 5000,
    poolAddress: '8KJp7Z8X9Y3A4B2C1D6E7F8G9H0I1J2K3L4M5N6O7P8Q9R0S1T2U3V4W5X6Y7Z8A',
    mintAddress: 'SMBtHCCC6RYRutFEPb4gZqeBLUZbMNhRKaMKZZLHi7W',
    website: 'https://solanamonkey.business/',
    twitter: 'https://twitter.com/SolanaMonkey',
  },
  {
    id: 'degenerate-ape-academy',
    name: 'Degenerate Ape Academy',
    symbol: 'DAPE',
    description: 'A collection of 10,000 unique Degenerate Apes living on Solana',
    image: 'https://arweave.net/26YdhY_eAzv26YdhY_eAzv26YdhY_eAzv26YdhY_eAzv',
    verified: true,
    floorPrice: 8.2,
    totalSupply: 10000,
    poolAddress: '9LKq8A9B0C1D2E3F4G5H6I7J8K9L0M1N2O3P4Q5R6S7T8U9V0W1X2Y3Z4A5B6C7D',
    mintAddress: 'DAPEcxWN3KWBzgXFGxR463dxfP1YjBxCHvwjy1MSCZfo',
    website: 'https://degenape.academy/',
    twitter: 'https://twitter.com/DegenApeAcademy',
  },
  {
    id: 'aurory',
    name: 'Aurory',
    symbol: 'AURY',
    description: 'Aurory NFT collection for the gaming ecosystem on Solana',
    image: 'https://arweave.net/KfkqXWpRzKFCKxTiuW5KfkqXWpRzKFCKxTiuW5',
    verified: true,
    floorPrice: 15.7,
    totalSupply: 10000,
    poolAddress: '7HJi6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6A7B8C9D0E1F2G3H4I5J',
    mintAddress: 'AURYydfxJib1ZkTir1Jn1J9ECYUtjb6rKQVmtYaixWPP',
    website: 'https://aurory.io/',
    twitter: 'https://twitter.com/AuroryProject',
  },
  {
    id: 'solana-punks',
    name: 'SolPunks',
    symbol: 'SPUNK',
    description: 'The first punks on Solana - 10,000 unique collectible characters',
    image: 'https://arweave.net/YQNMgdcYQNMgdcYQNMgdcYQNMgdcYQNMgdcYQNMgdc',
    verified: true,
    floorPrice: 6.3,
    totalSupply: 10000,
    poolAddress: '6GHi5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6A7B8C9D0E1F2G3H4I',
    mintAddress: 'PUNKydfxJib1ZkTir1Jn1J9ECYUtjb6rKQVmtYaixWPP',
    website: 'https://solpunks.com/',
    twitter: 'https://twitter.com/SolPunksNFT',
  },
  {
    id: 'thugbirdz',
    name: 'Thugbirdz',
    symbol: 'THUG',
    description: 'A collection of 3333 randomly generated Thugbirdz on Solana',
    image: 'https://arweave.net/ThugThugThugThugThugThugThugThugThugThug',
    verified: true,
    floorPrice: 4.1,
    totalSupply: 3333,
    poolAddress: '5FGh4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6A7B8C9D0E1F2G3H',
    mintAddress: 'THUGydfxJib1ZkTir1Jn1J9ECYUtjb6rKQVmtYaixWPP',
    website: 'https://thugbirdz.com/',
    twitter: 'https://twitter.com/thugbirdz',
  },
];

// API endpoints for real data
export const API_ENDPOINTS = {
  helius: 'https://devnet.helius-rpc.com',
  shyft: 'https://api.shyft.to/sol/v1',
  magicEden: 'https://api-devnet.magiceden.dev/v2',
  solscan: 'https://public-api.solscan.io',
  alchemy: 'https://solana-devnet.g.alchemy.com/v2',
  quicknode: 'https://your-endpoint.solana-devnet.quiknode.pro',
};

// Real collection addresses on devnet
export const DEVNET_COLLECTION_ADDRESSES = {
  'solana-monkey-business': 'SMBtHCCC6RYRutFEPb4gZqeBLUZbMNhRKaMKZZLHi7W',
  'degenerate-ape-academy': 'DAPEcxWN3KWBzgXFGxR463dxfP1YjBxCHvwjy1MSCZfo',
  'aurory': 'AURYydfxJib1ZkTir1Jn1J9ECYUtjb6rKQVmtYaixWPP',
  'solana-punks': 'PUNKydfxJib1ZkTir1Jn1J9ECYUtjb6rKQVmtYaixWPP',
  'thugbirdz': 'THUGydfxJib1ZkTir1Jn1J9ECYUtjb6rKQVmtYaixWPP',
};