[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_swap = "B4eBSHpFutVS5L2YtcwqvLKuEsENVQn5TH2uL6wwnt37"

[programs.devnet]
nft_swap = "B4eBSHpFutVS5L2YtcwqvLKuEsENVQn5TH2uL6wwnt37"

[programs.mainnet]
nft_swap = "B4eBSHpFutVS5L2YtcwqvLKuEsENVQn5TH2uL6wwnt37"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.29.0"